export const regformvalues = {
    firstname: "",
    lastname: "",
    email: "",
    phone: "",
    city: "",
    district: "",
    supply: "",
    hospital: "",
    wardbeds: 0,
    icubeds: 0,
    vantilators: 0,
    isoxygen: false,
    recoverydate: "",
    bloodgroup: "",
    disease: "",
    isage: false,
    isweight: false,
    isplasma: false,
    orgname: "",
    maplink: "",
    instalink: "",
    twitterlink: "",
    fblink: "",
    shopname: "",
    medname: "",
    istrue: false,
}

export const reqformvalues = {
    firstname: "",
    lastname: "",
    email: "",
    phone: "",
    city: "",
    district: "",
    supply: "",
    bloodgroup: "",
    medname: "",
    istrue: false,
}